# Use a base image Nginx
FROM nginx:latest

# Copie o arquivo HTML para dentro do contêiner
COPY client.html /usr/share/nginx/html/client.html

# Exponha a porta 80 8061 8062 9000 para acesso externo
EXPOSE 80 8061 8062 9000
